### ISSUE TITLE
Service: Amazon S3; Status Code: 403; Error Code: SignatureDoesNotMatch

### ISSUE THREAD

**Issue by kurvatch** [aws-observability/aws-otel-java-instrumentation#45]
**Describe the bug**
Instrumenting java agent for application interacting with S3 using aws-java-sdk-s3 causes SignatureDoesNotMatch error. 

**Steps to reproduce**
Instrument application interacting with S3 using aws-java-sdk-s3 library
       
 <dependency>
            <groupId>com.amazonaws</groupId>
            <artifactId>aws-java-sdk-s3</artifactId>
            <version>1.11.444</version>
        </dependency>

com.amazonaws.services.s3.model.AmazonS3Exception: null (Service: Amazon S3; Status Code: 403; Error Code: SignatureDoesNotMatch;

**Version of Java agent**
0.17.0-aws.1

**Comment by anuraaga** [comment]
Hi @kurvatch - can you share which S3 method you're using specifically? Also, do you have any other agents or proxies in your setup that could affect the AWS request?

**Comment by anuraaga** [comment]
By the way, we were lacking integration testing of AWS SDK v1 but I just added it and things look good - https://github.com/aws-observability/aws-otel-java-instrumentation/runs/2073606845?check_suite_focus=true

**Comment by kurvatch** [comment]
Thanks @anuraaga. Replacing aws agent with Opentelemetry Java agent works but issue when I switch. I am specifcally interested in AWS agent due to IDGenerators and my backend is X-Ray

Here is the stack trace		  
:"error getting file from s3 bucket: .com.amazonaws.services.s3.model.AmazonS3Exception: null 
(Service: Amazon S3; Status Code: 403; Error Code: SignatureDoesNotMatch; 
Request ID: tx00000000000003efb435e; S3 Extended Request ID: bb4e90)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1660)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1324)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1074)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:745)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:719)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:701)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:669)
at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:651)
at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:515)
at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4443)
at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4390)
at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:1427)
at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:1286)

**Comment by anuraaga** [comment]
Hi @kurvatch - sorry for the slow response. We've released 0.18.0 of the aws agent, can you see if it works for you? It's the same version as the upstream OpenTelemetry java agent so we'd expect the behavior to be the same.

**Comment by kurvatch** [comment]
Hi @anuraaga Problem still exist

**Comment by anuraaga** [comment]
Hi @kurvatch - we have this app that uses S3 in a limited way.
 https://www.github.com/aws-observability/aws-otel-java-instrumentation/tree/main/sample-apps%2Fspark-awssdkv1

It might not be the same APIs that you use. If you could provide a small sample repository that reproduces the issue we'll be able to see what's going on.
