### ISSUE TITLE
Null Pointer Exception with latest release

### ISSUE THREAD

**Issue by ajones-miovision** [aws-observability/aws-otel-java-instrumentation#46]
We updated to the latest release (0.17) of the aws-otel-java-instrumentation (from 0.15 previously) and now we see exceptions on startup and traces are not reported.

ERROR io.opentelemetry.javaagent.OpenTelemetryAgent
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at io.opentelemetry.javaagent.OpenTelemetryAgent.agentmain(OpenTelemetryAgent.java:64)
	at software.amazon.opentelemetry.javaagent.bootstrap.AwsAgentBootstrap.agentmain(AwsAgentBootstrap.java:28)
	at software.amazon.opentelemetry.javaagent.bootstrap.AwsAgentBootstrap.premain(AwsAgentBootstrap.java:24)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(Unknown Source)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(Unknown Source)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at io.opentelemetry.javaagent.bootstrap.AgentInitializer.startAgent(AgentInitializer.java:44)
	at io.opentelemetry.javaagent.bootstrap.AgentInitializer.initialize(AgentInitializer.java:30)
	... 13 more
Caused by: java.lang.ExceptionInInitializerError
	at io.opentelemetry.sdk.extension.aws.resource.Ec2ResourceProvider.createResource(Ec2ResourceProvider.java:16)
	at io.opentelemetry.sdk.autoconfigure.OpenTelemetrySdkAutoConfiguration.buildResource(OpenTelemetrySdkAutoConfiguration.java:77)
	at io.opentelemetry.sdk.autoconfigure.OpenTelemetrySdkAutoConfiguration.<clinit>(OpenTelemetrySdkAutoConfiguration.java:25)
	at io.opentelemetry.javaagent.tooling.OpenTelemetryInstaller.installAgentTracer(OpenTelemetryInstaller.java:36)
	at io.opentelemetry.javaagent.tooling.OpenTelemetryInstaller.beforeByteBuddyAgent(OpenTelemetryInstaller.java:27)
	at io.opentelemetry.javaagent.tooling.AgentInstaller.installComponentsBeforeByteBuddy(AgentInstaller.java:168)
	at io.opentelemetry.javaagent.tooling.AgentInstaller.installBytebuddyAgent(AgentInstaller.java:102)
	at io.opentelemetry.javaagent.tooling.AgentInstaller.installBytebuddyAgent(AgentInstaller.java:86)
	... 19 more
Caused by: java.lang.NullPointerException
	at io.opentelemetry.sdk.extension.aws.resource.Ec2Resource.buildResource(Ec2Resource.java:83)
	at io.opentelemetry.sdk.extension.aws.resource.Ec2Resource.buildResource(Ec2Resource.java:49)
	at io.opentelemetry.sdk.extension.aws.resource.Ec2Resource.<clinit>(Ec2Resource.java:31)
	... 27 more

Additional info:
We deploy to an EC2 backed ECS cluster with the aws otel collector running as a sidecar to each service.

**Comment by anuraaga** [comment]
Hi @ajones-miovision - sorry about this, this is a pretty silly bug, sent the fix at https://github.com/open-telemetry/opentelemetry-java/pull/3008

**Comment by ajones-miovision** [comment]
Perfect, thanks. I'll watch for when that change makes it's way from upstream to here.
