### ISSUE TITLE
More "intelligent" sampler option(s)

### ISSUE THREAD

**Issue by stnor** [aws-observability/aws-otel-java-instrumentation#56]
**Is your feature request related to a problem? Please describe.**
We've just migrated from AppD (javaagent) to X-Ray using the OTEL agent, v1.1. We're currently using `traceidratio` sampling and a 1/200 ratio.

This causes high frequency service calls to be over-represented in the sample set and low frequency services to be under-represented, or simply not present at all.

**Describe the solution you'd like**
I'd like a more sophisticated sampler that will collect data from all spans every time period, regardless of traffic.

See https://github.com/jaegertracing/jaeger/issues/365 for problem description and possible inspiration.

It seems like a common and basic need for instrumentation? Is anything planned upstream?

I should also add that we're running a monolitic application, so we can't configure each service with a different sample rate, as they are running in the same JVM / javaagent. But even in a micro service architecture, this problem would exist.
We do use Spring AOP to create custom spans for the Spring `@Service` business services.

I'd rather not have to roll my own OTEL java agent to address this issue... Are there any ways to address this from user-space?

**Comment by stnor** [comment]
Ok, I found some nice skeletons in the Jaeger extensions upstream. I built my own agent by adding my own classes to your project but I cannot get the SPI ```TracerProviderConfiguration.configureSampler()``` to pick up my SampleProvider.

```spiSamplers``` is length 0.

What am I missing?

```java

public class HelloSamplerProvider implements ConfigurableSamplerProvider {

    /**
     * Returns a {@link Sampler} that can be registered to OpenTelemetry by providing the property
     * value specified by {@link #getName()}.
     */
    @Override
    public Sampler createSampler(ConfigProperties config) {
        return new RateLimitingSampler(1);
    }

    /**
     * Returns the name of this sampler, which can be specified with the {@code otel.traces.sampler}
     * property to enable it. The name returned should NOT be the same as any other exporter name. If
     * the name does conflict with another exporter name, the resulting behavior is undefined and it
     * is explicitly unspecified which exporter will actually be used.
     */
    public String getName() {
        return "hello";
    }
}
```

**Comment by stnor** [comment]
Solved it. Missing runtime deps.
```
  implementation("io.opentelemetry.javaagent:opentelemetry-javaagent-spi")
  implementation("io.opentelemetry:opentelemetry-sdk-extension-autoconfigure:1.1.0-alpha")
```

I will roll my own agent for now. Is the plan to support X-Ray sampling rules any time soon?

**Comment by stnor** [comment]
```
/Library/Java/JavaVirtualMachines/amazon-corretto-15.jdk/Contents/Home/bin/java -javaagent:/Users/stnor/devel/src/aws-otel-java-instrumentation/otelagent/build/libs/aws-opentelemetry-agent-1.2.0-SNAPSHOT.jar -Dotel.resource.attributes=service.name=Nomp -Dotel.traces.sampler=hello -Dotel.traces.sampler.arg=0.99 -XX:TieredStopAtLevel=1 -noverify -Dspring.output.ansi.enabled=always -javaagent:/Applications/IntelliJ IDEA.app/Contents/lib/idea_rt.jar=52713:/Applications/IntelliJ IDEA.app/Contents/bin -Dcom.sun.management.jmxremote -Dspring.jmx.enabled=true -Dspring.liveBeansView.mbeanDomain -Dspring.application.admin.enabled=true -Dfile.encoding=UTF-8 -classpath /Users/stnor/devel/src/aws-otel-java-instrumentation/sample-apps/springboot/build/classes/java/main:/Users/stnor/devel/src/aws-otel-java-instrumentation/sample-apps/springboot/build/resources/main:/Users/stnor/.gradle/caches/modules-2/files-2.1/org.springframework.boot/spring-boot-starter-web/2.4.5/93cf2655557534e35723fbafa069bed2ee125832/spring-boot-starter-web-2.4.5.jar:/Users/stnor/.gradle/caches/modules-2/files-2.1/org.springframework.boot/spring-boot-starter/2.4.5/5f5398f459beb958fc2ece1a433420bf03cec628/spring-boot-starter-2.4.5.jar:/Users/stnor/.gradle/caches/modules-2/files-2.1/com.squareup.okhttp3/okhttp/4.9.1/51215279c3fe472c59b6b7dd7491e6ac2e28a81b/okhttp-4.9.1.jar:/Users/stnor/.gradle/caches/modules-2/files-2.1/software.amazon.awssdk/s3/2.16.44/2823e0bddff7961cd91e7b303c07a8be15af4a04/s3-2.16.44.jar:/Users/stnor/.gradle/caches/modules-2/files-2.1/io.opentelemetry/opentelemetry-api-metrics/1.1.0-alpha/26e86fd91d8418008322a755a27d562cbaae0c5d/opentelemetry-api-metrics-1.1.0-alpha.jar:/Users/stnor/.gradle/caches/modules-2/files-2.1/io.opentelemetry/opentelemetry-api/1.1.0/f8fe90192285c748a5581dce2b11dfb59366271f/opentelemetry-api-1.1.0.jar:/Users/stnor/.gradle/caches/modules-2/files-2.1/org.springframework.boot/spring-boot-starter-json/2.4.5/5c1623aa53adf10cd98884f60db2d9f5958dbc28/spring-boot-starter-json-2.4.5.jar:/Users/stnor/.gradle/caches/modules-2/files-2.1/org.springframework/spring-webmvc/5.3.6/a9bff0c28f90c73b0443de1d9299f32778ac8421/spring-webmvc-5.3.6.jar:/Users/stnor/.gradle/caches/modules-2/files-2.1/org.springframework/spring-web/5.3.6/f9290db7324194921c236ad9a940467f55304fa7/spring-web-5.3.6.jar:/Users/stnor/.gradle/caches/modules-2/files-2.1/org.springframework.boot/spring-boot-starter-tomcat/2.4.5/f562f975967df544afd88d8d10aa4bcd356b799d/spring-boot-starter-tomcat-2.4.5.jar:/Users/stnor/.gradle/caches/modules-2/files-2.1/org.springframework.boot/spring-boot-starter-logging/2.4.5/1537bbc2e8c6c9db806f9fa11ca7af394d7adacc/spring-boot-starter-logging-2.4.5.jar:/Users/stnor/.gradle/caches/modules-2/files-2.1/org.springframework.boot/spring-boot-autoconfigure/2.4.5/32887531b5a125d4840a08f9610aec766de73606/spring-boot-autoconfigure-2.4.5.jar:/Users/stnor/.gradle/caches/modules-2/files-2.1/org.springframework.boot/spring-boot/2.4.5/d9b82470df2e9549e448d7cef39e578d91f9867f/spring-boot-2.4.5.jar:/Users/stnor/.gradle/caches/modules-2/files-2.1/org.springframework/spring-core/5.3.6/8f91f60f628075701fde72bb5a43a33feeb27e93/spring-core-5.3.6.jar:/Users/stnor/.gradle/caches/modules-2/files-2.1/jakarta.annotation/jakarta.annotation-api/1.3.5/59eb84ee0d616332ff44aba065f3888cf002cd2d/jakarta.annotation-api-1.3.5.jar:/Users/stnor/.gradle/caches/modules-2/files-2.1/org.yaml/snakeyaml/1.27/359d62567480b07a679dc643f82fc926b100eed5/snakeyaml-1.27.jar:/Users/stnor/.gradle/caches/modules-2/files-2.1/com.squareup.okio/okio/2.8.0/49b64e09d81c0cc84b267edd0c2fd7df5a64c78c/okio-jvm-2.8.0.jar:/Users/stnor/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.4.32/461367948840adbb0839c51d91ed74ef4a9ccb52/kotlin-stdlib-1.4.32.jar:/Users/stnor/.gradle/caches/modules-2/files-2.1/software.amazon.awssdk/aws-xml-protocol/2.16.44/c5602cab248c75004df017743302137c02506f88/aws-xml-protocol-2.16.44.jar:/Users/stnor/.gradle/caches/modules-2/files-2.1/software.amazon.awssdk/protocol-core/2.16.44/325d756e547e771da41048942028923712f6affd/protocol-core-2.16.44.jar:/Users/stnor/.gradle/caches/modules-2/files-2.1/software.amazon.awssdk/aws-core/2.16.44/79b7ec8d2a6eeb3415ae1f41f052e590101d2aa8/aws-core-2.16.44.jar:/Users/stnor/.gradle/caches/modules-2/files-2.1/software.amazon.awssdk/auth/2.16.44/694d55cfed997bea115b23faab3235b2984f7d84/auth-2.16.44.jar:/Users/stnor/.gradle/caches/modules-2/files-2.1/software.amazon.awssdk/regions/2.16.44/f4a6dc548738140540ebc3cbf57031c1775d6b92/regions-2.16.44.jar:/Users/stnor/.gradle/caches/modules-2/files-2.1/software.amazon.awssdk/sdk-core/2.16.44/d51882bef770d890ecb71d5e17efb35542950e5c/sdk-core-2.16.44.jar:/Users/stnor/.gradle/caches/modules-2/files-2.1/software.amazon.awssdk/arns/2.16.44/9fcc104b48a25d5a4ecf3a78aebf290a06231ca5/arns-2.16.44.jar:/Users/stnor/.gradle/caches/modules-2/files-2.1/software.amazon.awssdk/profiles/2.16.44/76f92983842db31838732bf2abaaf03db6419cee/profiles-2.16.44.jar:/Users/stnor/.gradle/caches/modules-2/files-2.1/software.amazon.awssdk/http-client-spi/2.16.44/ef6c5cd3ee203ed9f048c032e17140cd54a20eb7/http-client-spi-2.16.44.jar:/Users/stnor/.gradle/caches/modules-2/files-2.1/software.amazon.awssdk/metrics-spi/2.16.44/e813a4dbb98240140459db02ea8fa0f7f80fa219/metrics-spi-2.16.44.jar:/Users/stnor/.gradle/caches/modules-2/files-2.1/software.amazon.awssdk/utils/2.16.44/7c7ad1304c01a1f02334ae691921cdc9892d4f63/utils-2.16.44.jar:/Users/stnor/.gradle/caches/modules-2/files-2.1/software.amazon.awssdk/annotations/2.16.44/8cd61ea55488a07d9bde6581d8d922be8b6b8db9/annotations-2.16.44.jar:/Users/stnor/.gradle/caches/modules-2/files-2.1/io.opentelemetry/opentelemetry-context/1.1.0/682526f8b722f72ac30ab19c7e5e10004cbc8c4e/opentelemetry-context-1.1.0.jar:/Users/stnor/.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.datatype/jackson-datatype-jdk8/2.12.3/77424ea087313312e308dae5ff8445608aabb5e1/jackson-datatype-jdk8-2.12.3.jar:/Users/stnor/.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.datatype/jackson-datatype-jsr310/2.12.3/f69c636438dcf19c49960c1fe8901320ab85f989/jackson-datatype-jsr310-2.12.3.jar:/Users/stnor/.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.module/jackson-module-parameter-names/2.12.3/592a882beaf1bd57b8fe960b937a2706b090b4d7/jackson-module-parameter-names-2.12.3.jar:/Users/stnor/.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.core/jackson-databind/2.12.3/d6153f8fc60c479ab0f9efb35c034526436a4953/jackson-databind-2.12.3.jar:/Users/stnor/.gradle/caches/modules-2/files-2.1/org.springframework/spring-context/5.3.6/d99d3931528309a4ff49b7d18f76f1657aa16c52/spring-context-5.3.6.jar:/Users/stnor/.gradle/caches/modules-2/files-2.1/org.springframework/spring-aop/5.3.6/510d9afcfce1fa9a2086906ab87b9989973c251c/spring-aop-5.3.6.jar:/Users/stnor/.gradle/caches/modules-2/files-2.1/org.springframework/spring-beans/5.3.6/99cc944fb3454410b47fc98d4b148a6205bfe8f6/spring-beans-5.3.6.jar:/Users/stnor/.gradle/caches/modules-2/files-2.1/org.springframework/spring-expression/5.3.6/33ba1d8dfaab0fd60ce4213a206f5d4fc77ce27a/spring-expression-5.3.6.jar:/Users/stnor/.gradle/caches/modules-2/files-2.1/org.glassfish/jakarta.el/3.0.3/dab46ee1ee23f7197c13d7c40fce14817c9017df/jakarta.el-3.0.3.jar:/Users/stnor/.gradle/caches/modules-2/files-2.1/org.apache.tomcat.embed/tomcat-embed-websocket/9.0.45/5cefd0aab62e2938f51110ebeb557b30ed5abab/tomcat-embed-websocket-9.0.45.jar:/Users/stnor/.gradle/caches/modules-2/files-2.1/org.apache.tomcat.embed/tomcat-embed-core/9.0.45/8fb7d78b14e2deb8fec430498c64418ec0a2d983/tomcat-embed-core-9.0.45.jar:/Users/stnor/.gradle/caches/modules-2/files-2.1/org.apache.logging.log4j/log4j-to-slf4j/2.14.1/ce8a86a3f50a4304749828ce68e7478cafbc8039/log4j-to-slf4j-2.14.1.jar:/Users/stnor/.gradle/caches/modules-2/files-2.1/ch.qos.logback/logback-classic/1.2.3/7c4f3c474fb2c041d8028740440937705ebb473a/logback-classic-1.2.3.jar:/Users/stnor/.gradle/caches/modules-2/files-2.1/org.slf4j/jul-to-slf4j/1.7.30/d58bebff8cbf70ff52b59208586095f467656c30/jul-to-slf4j-1.7.30.jar:/Users/stnor/.gradle/caches/modules-2/files-2.1/org.springframework/spring-jcl/5.3.6/53ddfc5cfdf438a1d3346fc2912c3e3049a8cb76/spring-jcl-5.3.6.jar:/Users/stnor/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-common/1.4.32/ef50bfa2c0491a11dcc35d9822edbfd6170e1ea2/kotlin-stdlib-common-1.4.32.jar:/Users/stnor/.gradle/caches/modules-2/files-2.1/org.jetbrains/annotations/13.0/919f0dfe192fb4e063e7dacadee7f8bb9a2672a9/annotations-13.0.jar:/Users/stnor/.gradle/caches/modules-2/files-2.1/software.amazon.awssdk/aws-query-protocol/2.16.44/e50a08f009e63237d6cbfefd68a159aff2a952b6/aws-query-protocol-2.16.44.jar:/Users/stnor/.gradle/caches/modules-2/files-2.1/org.slf4j/slf4j-api/1.7.30/b5a4b6d16ab13e34a88fae84c35cd5d68cac922c/slf4j-api-1.7.30.jar:/Users/stnor/.gradle/caches/modules-2/files-2.1/software.amazon.eventstream/eventstream/1.0.1/6ff8649dffc5190366ada897ba8525a836297784/eventstream-1.0.1.jar:/Users/stnor/.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.core/jackson-annotations/2.12.3/7275513412694a1aafd08c0287f48469fa0e6e17/jackson-annotations-2.12.3.jar:/Users/stnor/.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.core/jackson-core/2.12.3/deb23fe2a7f2b773e18ced2b50d4acc1df8fa366/jackson-core-2.12.3.jar:/Users/stnor/.gradle/caches/modules-2/files-2.1/org.reactivestreams/reactive-streams/1.0.3/d9fb7a7926ffa635b3dcaa5049fb2bfa25b3e7d0/reactive-streams-1.0.3.jar:/Users/stnor/.gradle/caches/modules-2/files-2.1/org.apache.logging.log4j/log4j-api/2.14.1/cd8858fbbde69f46bce8db1152c18a43328aae78/log4j-api-2.14.1.jar:/Users/stnor/.gradle/caches/modules-2/files-2.1/ch.qos.logback/logback-core/1.2.3/864344400c3d4d92dfeb0a305dc87d953677c03c/logback-core-1.2.3.jar:/Users/stnor/.gradle/caches/modules-2/files-2.1/software.amazon.awssdk/apache-client/2.16.44/19a73302137a128d769d4ab2aabb9c85a801f4e6/apache-client-2.16.44.jar:/Users/stnor/.gradle/caches/modules-2/files-2.1/software.amazon.awssdk/netty-nio-client/2.16.44/a9b3cde12419b603fc8b4fdbc96bd089781436dc/netty-nio-client-2.16.44.jar:/Users/stnor/.gradle/caches/modules-2/files-2.1/org.apache.httpcomponents/httpclient/4.5.13/e5f6cae5ca7ecaac1ec2827a9e2d65ae2869cada/httpclient-4.5.13.jar:/Users/stnor/.gradle/caches/modules-2/files-2.1/org.apache.httpcomponents/httpcore/4.4.14/9dd1a631c082d92ecd4bd8fd4cf55026c720a8c1/httpcore-4.4.14.jar:/Users/stnor/.gradle/caches/modules-2/files-2.1/com.typesafe.netty/netty-reactive-streams-http/2.0.4/5f4d3ea06767bcd54159e4ce901565dd974bdc8a/netty-reactive-streams-http-2.0.4.jar:/Users/stnor/.gradle/caches/modules-2/files-2.1/io.netty/netty-codec-http2/4.1.63.Final/294e90696d8d6e20c889511d2484b37158cb9caa/netty-codec-http2-4.1.63.Final.jar:/Users/stnor/.gradle/caches/modules-2/files-2.1/io.netty/netty-codec-http/4.1.63.Final/f8c9b159dcb76452dc98a370a5511ff993670419/netty-codec-http-4.1.63.Final.jar:/Users/stnor/.gradle/caches/modules-2/files-2.1/io.netty/netty-handler/4.1.63.Final/879a43c2325b08e92e8967218b6ddb0ed4b7a0d3/netty-handler-4.1.63.Final.jar:/Users/stnor/.gradle/caches/modules-2/files-2.1/io.netty/netty-codec/4.1.63.Final/d4d2fccea88c80e56d59ce1053c53df0f9f4f5db/netty-codec-4.1.63.Final.jar:/Users/stnor/.gradle/caches/modules-2/files-2.1/io.netty/netty-transport-native-epoll/4.1.63.Final/98d898362dd9a00eb23e2857a49cb15ff37353dc/netty-transport-native-epoll-4.1.63.Final-linux-x86_64.jar:/Users/stnor/.gradle/caches/modules-2/files-2.1/io.netty/netty-transport/4.1.63.Final/9a8bbe1ba082c9434e6f524d3864a53f340f2df/netty-transport-4.1.63.Final.jar:/Users/stnor/.gradle/caches/modules-2/files-2.1/io.netty/netty-buffer/4.1.63.Final/40028ce5ac7c43f1c9a1439f74637cad04013e23/netty-buffer-4.1.63.Final.jar:/Users/stnor/.gradle/caches/modules-2/files-2.1/io.netty/netty-common/4.1.63.Final/e1206b46384d4dcbecee2901f18ce65ecf02e8a4/netty-common-4.1.63.Final.jar:/Users/stnor/.gradle/caches/modules-2/files-2.1/commons-codec/commons-codec/1.15/49d94806b6e3dc933dacbd8acb0fdbab8ebd1e5d/commons-codec-1.15.jar:/Users/stnor/.gradle/caches/modules-2/files-2.1/com.typesafe.netty/netty-reactive-streams/2.0.4/f77c8eaa7d5e2f2160b6d21ba385cf726f164b2/netty-reactive-streams-2.0.4.jar:/Users/stnor/.gradle/caches/modules-2/files-2.1/io.netty/netty-resolver/4.1.63.Final/d07cd47c101dfa655d6d5cc304d523742fd78ca8/netty-resolver-4.1.63.Final.jar:/Users/stnor/.gradle/caches/modules-2/files-2.1/io.netty/netty-transport-native-unix-common/4.1.63.Final/85bd91382ec54b300ad3ff59efccbb4fccb22a88/netty-transport-native-unix-common-4.1.63.Final.jar com.amazon.sampleapp.DemoApplication
OpenJDK 64-Bit Server VM warning: Options -Xverify:none and -noverify were deprecated in JDK 13 and will likely be removed in a future release.
***class software.amazon.opentelemetry.javaagent.bootstrap.HelloSamplerProvider
OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
[opentelemetry.auto.trace 2021-05-16 10:33:07:973 +0200] [main] INFO io.opentelemetry.javaagent.tooling.VersionLogger - opentelemetry-javaagent - version: 1.2.0-aws-SNAPSHOT
ERROR io.opentelemetry.javaagent.OpenTelemetryAgent
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at io.opentelemetry.javaagent.OpenTelemetryAgent.agentmain(OpenTelemetryAgent.java:64)
	at software.amazon.opentelemetry.javaagent.bootstrap.AwsAgentBootstrap.agentmain(AwsAgentBootstrap.java:29)
	at software.amazon.opentelemetry.javaagent.bootstrap.AwsAgentBootstrap.premain(AwsAgentBootstrap.java:24)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:513)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:525)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at io.opentelemetry.javaagent.bootstrap.AgentInitializer.startAgent(AgentInitializer.java:44)
	at io.opentelemetry.javaagent.bootstrap.AgentInitializer.initialize(AgentInitializer.java:30)
	... 13 more
Caused by: io.opentelemetry.sdk.autoconfigure.ConfigurationException: Unrecognized value for otel.traces.sampler: hello```

What am I missing?

Code at https://github.com/stnor/aws-otel-java-instrumentation/tree/main/otelagent/src/main/java/software/amazon/opentelemetry/javaagent/bootstrap

**Comment by anuraaga** [comment]
Hi @stnor 

For the issue of the agent, I didn't confirm myself but believe the problem is putting the code in the `otelagent` folder, you should put it in the `awsagentprovider` folder. `otelagent` is just the initialization of the agent, which creates a separate `ClassLoader` with the actual SDK, and that includes what's in `awsagentprovider`. That is controlled by this line

https://github.com/stnor/aws-otel-java-instrumentation/blob/main/otelagent/build.gradle.kts#L58

As for sampling in general, its indeed an area OTel still needs to spec out much better. Out of curiosity, can you clarify your priority of these aspects

1) Rate limiting, leaky bucket sampler to allow full sampling for lower QPS services, as opposed to random sampling which is always random
2) Per-operation sampling where different HTTP paths for example have different sampling properties
3) Remote sampling configuration, where you can update properties on a server and have that automatically reflected on running servers without restart

We will want to get some issues filed in `opentelemetry-specification` based on what can help and the priorities. In the meantime, I think you having full control by writing a `Sampler` is a good idea and hopefully my suggestion unblocks you. Having some real code based on what works well for you will help frame discussions in the spec even better.

**Comment by anuraaga** [comment]
Ah also just noticed the repo you linked seems to be missing the `META-INF/services` file to register the sampler provider as an SPI implementation.

**Comment by stnor** [comment]
Hi @anuraaga

Thanks for the feedback, and taking the time to look at this. I will revisit the code later today.

As for my priorities; Remote sampling configuration is not important at all. Runtime changes isn't important either.

Per operation-configuration is my top prio as things stand, but I think that wouldn't be needed (I think) if the sampler would try to meet a budget with a lower and upper bound of traces per time unit per operation automatically. But I am not a statistician.

AppDynamics keeps track of typical invocation response times per operation and samples (more) based on deviations, which is very useful, https://docs.appdynamics.com/display/PRO21/Diagnostic+Sessions

**Comment by stnor** [comment]
Got the sampler registration to work now. Thanks. Did a reset, and created a new branch for this work in my fork. https://github.com/stnor/aws-otel-java-instrumentation/tree/nomp-sampler

**Comment by stnor** [comment]
I will try this simple hack to start with. When testing my code, I realised I should be using a parent based sampler.
https://github.com/stnor/aws-otel-java-instrumentation/blob/nomp-sampler/awsagentprovider/src/main/java/se/nomp/instrumentation/otel/providers/NompParentBasedSampler.java
